### PR TITLE
Refactored FallbackConfigurationLoader to be able to specify the 'last-chance' fallback

### PR DESCRIPTION
**Pull request by stacycurl**
Also made loadOrDie pass along the 'loader' which was effectively unused before.

### CODE REVIEW

**Comment by stacycurl** [comment]
Btw, there's no 'I' in "denial" & no Raymanoz in UK, so your profile is out of date, waaah.

:P

**Comment by stacycurl** [comment]
The reason for this change is I want to unit test my own config, eg, given
my.conf contains

```
  foo=oof
  boo=${?oob}
```

and I have code:

```
   case class AppConf(foo: String, boo: String) {
     def this(config: Config) = this(config.getString("foo"), config.getString("boo"))
   }
```

I want to test that AppConf loads but without having to muck about with system props.

**Comment by raymanoz** [comment]
😁

**Comment by stacycurl** [comment]
Thanks !

**Comment by raymanoz** [comment]
No worries. Almost forgot about it! :)

**Pull request merged**
